/**
 * sensei remove
 *
 * Removes everything sensei installed: MCP entries from all ACP configs,
 * sensei hooks from settings files, and generated skill files.
 *
 * Scope:
 *   (default)  global — ~/.claude, ~/.cursor, ~/.codeium, etc.
 *   --local    repo-scoped — .claude/ and .sensei/ in the current repo only
 *   --all      global + also wipe ~/.sensei/ data directory
 *   --dry-run  print what would be removed without making changes
 */

import { readFile, writeFile, readdir, rm } from "fs/promises";
import { existsSync } from "fs";
import { join } from "path";
import { homedir } from "os";

export interface RemoveOptions {
  local?: boolean;
  all?: boolean;
  dryRun?: boolean;
}

// ── ACP config locations ─────────────────────────────────────────────────────

interface AcpConfig {
  id: string;
  path: string;       // relative to HOME
  mcpKey: string;     // "mcpServers" | "mcp"
}

const ACP_CONFIGS: AcpConfig[] = [
  { id: "claude-desktop", path: "Library/Application Support/Claude/claude_desktop_config.json", mcpKey: "mcpServers" },
  { id: "claude-code",    path: ".claude/settings.json",                                         mcpKey: "mcpServers" },
  { id: "cursor",         path: ".cursor/mcp.json",                                              mcpKey: "mcpServers" },
  { id: "windsurf",       path: ".codeium/windsurf/mcp_config.json",                             mcpKey: "mcpServers" },
  { id: "zed",            path: ".config/zed/settings.json",                                     mcpKey: "mcpServers" },
  { id: "kiro",           path: ".kiro/settings/mcp.json",                                       mcpKey: "mcpServers" },
  { id: "opencode",       path: ".config/opencode/opencode.json",                                mcpKey: "mcp"        },
];

// Skill categories generated by sensei (matches AgentSkillFile["category"] union)
const SKILL_SUFFIXES = ["-orientation.md", "-workflow.md", "-context.md", "-patterns.md"];
// Lib skills: *-lib-*.md
const LIB_SKILL_RE = /-lib-.+\.md$/;

// ── Helpers ──────────────────────────────────────────────────────────────────

type JsonObject = Record<string, unknown>;

async function readJson(path: string): Promise<JsonObject | null> {
  try {
    return JSON.parse(await readFile(path, "utf-8")) as JsonObject;
  } catch {
    return null;
  }
}

async function writeJson(path: string, data: JsonObject, dry: boolean): Promise<void> {
  if (dry) return;
  await writeFile(path, JSON.stringify(data, null, 2));
}

function isSenseiHookEntry(entry: unknown): boolean {
  if (!entry || typeof entry !== "object") return false;
  const obj = entry as Record<string, unknown>;
  const hooks = Array.isArray(obj.hooks) ? obj.hooks : [];
  return hooks.some(h => {
    if (!h || typeof h !== "object") return false;
    const cmd = (h as Record<string, unknown>).command;
    return typeof cmd === "string" && (cmd.includes("sensei") || cmd.includes("senseid"));
  });
}

// ── MCP removal ──────────────────────────────────────────────────────────────

async function removeMcpEntry(
  configPath: string,
  mcpKey: string,
  dry: boolean,
): Promise<string | null> {
  if (!existsSync(configPath)) return null;
  const cfg = await readJson(configPath);
  if (!cfg) return null;

  const mcpSection = cfg[mcpKey] as JsonObject | undefined;
  if (!mcpSection || !("sensei" in mcpSection)) return null;

  if (!dry) {
    delete mcpSection.sensei;
    cfg[mcpKey] = mcpSection;
    await writeJson(configPath, cfg, false);
  }
  return configPath;
}

// ── Hook removal ──────────────────────────────────────────────────────────────

async function removeSenseiHooks(
  settingsPath: string,
  dry: boolean,
): Promise<boolean> {
  if (!existsSync(settingsPath)) return false;
  const cfg = await readJson(settingsPath);
  if (!cfg) return false;

  const hooksSection = cfg.hooks as Record<string, unknown[]> | undefined;
  if (!hooksSection) return false;

  let changed = false;
  for (const event of Object.keys(hooksSection)) {
    const entries = hooksSection[event];
    if (!Array.isArray(entries)) continue;
    const filtered = entries.filter(e => !isSenseiHookEntry(e));
    if (filtered.length !== entries.length) {
      hooksSection[event] = filtered;
      changed = true;
    }
  }

  if (changed && !dry) {
    cfg.hooks = hooksSection;
    await writeJson(settingsPath, cfg, false);
  }
  return changed;
}

// ── Skill removal ─────────────────────────────────────────────────────────────

async function removeSenseiSkills(
  skillsDir: string,
  dry: boolean,
): Promise<string[]> {
  if (!existsSync(skillsDir)) return [];
  const entries = await readdir(skillsDir);
  const toRemove = entries.filter(
    e => SKILL_SUFFIXES.some(s => e.endsWith(s)) || LIB_SKILL_RE.test(e),
  );
  if (!dry) {
    for (const f of toRemove) {
      await rm(join(skillsDir, f), { force: true });
    }
  }
  return toRemove.map(f => join(skillsDir, f));
}

// ── Main ─────────────────────────────────────────────────────────────────────

export async function remove(cwd: string, opts: RemoveOptions = {}): Promise<void> {
  const dry = opts.dryRun ?? false;
  const local = opts.local ?? false;
  const h = homedir();

  const removed: string[] = [];
  const skipped: string[] = [];

  if (dry) console.log("sensei remove --dry-run (no files will be changed)\n");

  if (local) {
    // ── Local / repo-scoped cleanup ──────────────────────────────────────────

    const localSettings = join(cwd, ".claude", "settings.json");
    const localSkills = join(cwd, ".claude", "skills");
    const localBenchmark = join(cwd, ".sensei", "benchmark");

    console.log(`scope: local  (${cwd})`);

    const hooksRemoved = await removeSenseiHooks(localSettings, dry);
    if (hooksRemoved) {
      removed.push(`hooks → ${localSettings}`);
    } else {
      skipped.push(`hooks (not found or none installed) → ${localSettings}`);
    }

    const skillFiles = await removeSenseiSkills(localSkills, dry);
    if (skillFiles.length > 0) {
      removed.push(...skillFiles.map(f => `skill → ${f}`));
    } else {
      skipped.push(`skills (none found) → ${localSkills}`);
    }

    if (existsSync(localBenchmark)) {
      if (!dry) await rm(localBenchmark, { recursive: true, force: true });
      removed.push(`benchmark data → ${localBenchmark}`);
    }

  } else {
    // ── Global cleanup ───────────────────────────────────────────────────────

    console.log("scope: global");

    // MCP entries
    console.log("\nMCP configs:");
    for (const acp of ACP_CONFIGS) {
      const configPath = join(h, acp.path);
      const r = await removeMcpEntry(configPath, acp.mcpKey, dry);
      if (r) {
        removed.push(`mcp[${acp.id}] → ${configPath}`);
        console.log(`  ✓ ${acp.id}`);
      } else {
        skipped.push(`mcp[${acp.id}] (not installed)`);
        console.log(`  – ${acp.id} (not installed)`);
      }
    }

    // Hooks (Claude Code only — other ACPs don't have sensei hooks yet)
    console.log("\nHooks:");
    const claudeSettings = join(h, ".claude", "settings.json");
    const hooksRemoved = await removeSenseiHooks(claudeSettings, dry);
    if (hooksRemoved) {
      removed.push(`hooks → ${claudeSettings}`);
      console.log("  ✓ claude-code hooks");
    } else {
      skipped.push("hooks (none installed)");
      console.log("  – claude-code hooks (none installed)");
    }

    // Global skills (~/.claude/skills/)
    console.log("\nSkills:");
    const globalSkills = join(h, ".claude", "skills");
    const skillFiles = await removeSenseiSkills(globalSkills, dry);
    if (skillFiles.length > 0) {
      removed.push(...skillFiles.map(f => `skill → ${f}`));
      console.log(`  ✓ ${skillFiles.length} skill file(s) from ${globalSkills}`);
    } else {
      skipped.push("skills (none found)");
      console.log(`  – no sensei skill files in ${globalSkills}`);
    }

    // ~/.sensei/ data directory (only with --all)
    if (opts.all) {
      const senseiData = join(h, ".sensei");
      if (existsSync(senseiData)) {
        if (!dry) await rm(senseiData, { recursive: true, force: true });
        removed.push(`data → ${senseiData}`);
        console.log(`\n  ✓ removed ${senseiData}`);
      }
    } else {
      console.log(`\n  (skipping ~/.sensei/ data — use --all to remove)`);
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────────

  console.log(`\n${dry ? "would remove" : "removed"}: ${removed.length} item(s)`);
  if (removed.length > 0 && dry) {
    for (const r of removed) console.log(`  ${r}`);
  }
}
