import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

// Hardcoded seed data — real impl reads from ~/.sensei/sensei.db
// and scans ~/Developer + ~/Work
export const GET: RequestHandler = () => {
  return json([
    {
      id: 'proj-001',
      kind: 'repo',
      name: 'sensei',
      path: '~/Developer/sensei',
      description: 'Claude Code lifecycle guide — local-first desktop app',
      maturity: 3,
      language: 'TypeScript',
      activePhase: 'Implementation',
      lastActivity: '2 hours ago',
      sessionCount: 24,
      cardCount: 12,
      symbolCount: 4821,
      ftrScore: 0.72,
    },
    {
      id: 'proj-002',
      kind: 'repo',
      name: 'rokkit',
      path: '~/Developer/rokkit',
      description: 'Design system and component library for Sensei ecosystem',
      maturity: 4,
      language: 'TypeScript',
      activePhase: 'Mature',
      lastActivity: 'Yesterday',
      sessionCount: 18,
      cardCount: 8,
      symbolCount: 2340,
      ftrScore: 0.85,
    },
    {
      id: 'proj-003',
      kind: 'repo',
      name: 'kavach',
      path: '~/Developer/kavach',
      description: 'Authentication middleware for SvelteKit applications',
      maturity: 4,
      language: 'TypeScript',
      activePhase: 'Maintenance',
      lastActivity: '3 days ago',
      sessionCount: 31,
      cardCount: 5,
      symbolCount: 1890,
      ftrScore: 0.91,
    },
    {
      id: 'proj-004',
      kind: 'repo',
      name: 'api-gateway',
      path: '~/Work/api-gateway',
      description: 'Internal API gateway and rate limiting service',
      maturity: 2,
      language: 'Go',
      activePhase: 'Design',
      lastActivity: '1 week ago',
      sessionCount: 7,
      cardCount: 14,
      symbolCount: 980,
      ftrScore: 0.68,
    },
    {
      id: 'proj-005',
      kind: 'idea',
      name: 'sensei-mobile',
      path: null,
      description: 'Mobile companion app for session review and approvals on the go',
      maturity: 1,
      language: null,
      activePhase: 'Ideation',
      lastActivity: '5 days ago',
      sessionCount: 0,
      cardCount: 4,
      symbolCount: 0,
      ftrScore: null,
    },
    {
      id: 'proj-006',
      kind: 'repo',
      name: 'dbd',
      path: '~/Developer/dbd',
      description: 'Database schema DDL management and migration tool',
      maturity: 3,
      language: 'TypeScript',
      activePhase: 'Implementation',
      lastActivity: '4 days ago',
      sessionCount: 11,
      cardCount: 6,
      symbolCount: 1240,
      ftrScore: 0.78,
    },
  ]);
};
