import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { svelteTesting } from '@testing-library/svelte/vite';

// Standalone vitest config for component/state specs. Kept separate from
// vite.config.ts so the kavach + SvelteKit plugins (which need the virtual
// $kavach/* modules and a running dev server) don't load during unit tests.
export default defineConfig({
	plugins: [svelte(), svelteTesting()],
	test: {
		environment: 'jsdom',
		// Include the `.spec.svelte.ts` suffix too so rune-store specs (state modules
		// that use $state and must run through the Svelte compiler) are picked up —
		// matching app/vitest.config.ts. The `{test,spec}.{js,ts}` glob alone misses
		// `*.spec.svelte.ts`.
		include: ['src/**/*.{test,spec}.{js,ts}', 'src/**/*.spec.svelte.ts'],
		globals: true,
		setupFiles: [],
		// lcov for the qlty coverage upload (paths relative to dojo/, so CI adds
		// the `dojo` prefix). `bun run test --coverage` writes ./coverage.
		coverage: {
			provider: 'v8',
			reporter: ['text', 'lcov'],
			reportsDirectory: './coverage',
			include: ['src/**'],
			// paraglide/** is gitignored, generated i18n output (paraglide-js compile);
			// it's on disk at test time but isn't ours to cover.
			exclude: ['src/**/*.{test,spec}.*', 'src/**/test-stubs/**', 'src/lib/paraglide/**']
		}
	},
	resolve: {
		alias: {
			$lib: new URL('./src/lib', import.meta.url).pathname,
			// $env/dynamic/public isn't generated outside the SvelteKit plugin; point
			// it at a stub so the triage API client imports cleanly under vitest.
			'$env/dynamic/public': new URL(
				'./src/lib/test-stubs/env-dynamic-public.ts',
				import.meta.url
			).pathname,
			// $env/dynamic/private — same reason; server-only modules (dojo-supabase)
			// read private env at call time, so importing the real module under vitest
			// needs this stub. Specs mock `dojoDb` itself, so no real key is used.
			'$env/dynamic/private': new URL(
				'./src/lib/test-stubs/env-dynamic-private.ts',
				import.meta.url
			).pathname,
			// $app/paths (resolve) likewise isn't generated under vitest; a pass-through
			// stub lets components that build hrefs (nav, top bar) render in specs.
			'$app/paths': new URL('./src/lib/test-stubs/app-paths.ts', import.meta.url).pathname,
			// $app/navigation (goto/invalidateAll) — same reason; the LogoutButton
			// calls goto() on click, so the kit shells need it stubbed to render.
			'$app/navigation': new URL(
				'./src/lib/test-stubs/app-navigation.ts',
				import.meta.url
			).pathname,
			// $kavach/providers is generated by @kavach/vite (absent under vitest);
			// @kavach/ui's real components need the kavach context + @rokkit auth
			// stack. Stub both so DojoSignIn render specs work (they assert the
			// sign-in options appear, not the real OAuth flow).
			'$kavach/providers': new URL(
				'./src/lib/test-stubs/kavach-providers.ts',
				import.meta.url
			).pathname,
			'@kavach/ui': new URL('./src/lib/test-stubs/kavach-ui.ts', import.meta.url).pathname
		}
	}
});
