import { readFile, writeFile } from "fs/promises";
import { existsSync } from "fs";
import { dirname, basename } from "path";
import type { SymbolMap, LlmSpec, LlmsTxtSection } from "@sensei/shared";
import { senseiPath } from "@sensei/shared";

// ─── Section building ─────────────────────────────────────────────────────────

export function buildSections(symbolMap: SymbolMap, entryPointPaths: string[]): LlmsTxtSection[] {
  const allPaths = Object.keys(symbolMap);
  const entrySet = new Set(entryPointPaths.filter(p => p in symbolMap));

  const sections: LlmsTxtSection[] = [];

  if (entrySet.size > 0) {
    sections.push({ name: "Entry Points", sources: [...entrySet] });
  }

  const dirMap = new Map<string, string[]>();
  for (const p of allPaths) {
    if (entrySet.has(p)) continue;
    const dir = dirname(p);
    if (!dirMap.has(dir)) dirMap.set(dir, []);
    dirMap.get(dir)!.push(p);
  }

  for (const [dir, files] of [...dirMap.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    sections.push({ name: dir, sources: files.sort() });
  }

  return sections;
}

// ─── Section rendering ────────────────────────────────────────────────────────

const EXPORT_PREFIX_RE = /^export\s+(async\s+)?(function|class|const|type|interface|enum)\s+/;

export function renderSection(name: string, sources: string[], symbolMap: SymbolMap): string {
  const lines = [`## ${name}`];

  for (const src of sources) {
    const entry = symbolMap[src];
    const fileName = basename(src);
    const href = src;

    if (!entry || entry.L0.length === 0) {
      lines.push(`- [${fileName}](${href})`);
      continue;
    }

    const names = entry.L0
      .slice(0, 5)
      .map(sig => sig.replace(EXPORT_PREFIX_RE, "").split(/[\s(<:]/)[0].trim())
      .filter(Boolean);

    lines.push(`- [${fileName}](${href}): ${names.join(", ")}`);
  }

  return lines.join("\n");
}

// ─── Parsing ──────────────────────────────────────────────────────────────────

export function parseLlmsTxt(content: string): Record<string, string> {
  if (!content.trim()) return {};

  const result: Record<string, string> = {};
  const parts = content.split(/\n(?=## )/);

  for (const part of parts) {
    const firstLine = part.split("\n")[0];
    if (!firstLine.startsWith("## ")) continue;
    const sectionName = firstLine.slice(3).trim();
    const body = part.slice(firstLine.length + 1).trimEnd();
    result[sectionName] = body;
  }

  return result;
}

// ─── Full generation ──────────────────────────────────────────────────────────

export async function generateLlmsTxt(
  repoPath: string,
  spec: LlmSpec,
  symbolMap: SymbolMap,
  changedFiles: Set<string>,
): Promise<LlmsTxtSection[]> {
  const entryPointPaths = spec.entry_points.map(e => e.path);
  const sections = buildSections(symbolMap, entryPointPaths);

  const outPath = senseiPath(repoPath, "llms.txt");
  let existingSections: Record<string, string> = {};
  if (existsSync(outPath)) {
    const existing = await readFile(outPath, "utf-8");
    existingSections = parseLlmsTxt(existing);
  }

  const header = `# ${spec.project}\n> ${spec.description}`;

  const renderedParts: string[] = [header];
  for (const section of sections) {
    const sourcesChanged = section.sources.some(s => changedFiles.has(s));
    if (!sourcesChanged && existingSections[section.name] !== undefined) {
      renderedParts.push(`## ${section.name}\n${existingSections[section.name]}`);
    } else {
      renderedParts.push(renderSection(section.name, section.sources, symbolMap));
    }
  }

  renderedParts.push("> Generated by sensei");

  await writeFile(outPath, renderedParts.join("\n\n"));

  return sections;
}
