// Test stub for the build-time virtual `$kavach/providers` (generated by
// @kavach/vite from kavach.config.js — absent under vitest). Mirrors the
// configured providers so DojoSignIn renders every sign-in option.
export const providers = [
	{ name: 'github', mode: 'oauth', label: 'Continue with GitHub', scopes: ['read:org', 'user:email'] },
	{ name: 'magic', mode: 'otp', label: 'Email me a magic link' },
	{ name: 'email', mode: 'password', label: 'Sign in with password' }
];
