use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::Json,
};
use serde::Deserialize;
use crate::api::state::AppState;

// Re-use TagBody from workspace
use super::workspace::TagBody;

// ── Solutions CRUD ──────────────────────────────────────────────────────────

pub(crate) async fn list_solutions(State(state): State<AppState>) -> Result<Json<serde_json::Value>, StatusCode> {
    let projects = state.pg.list_projects().await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    // Enrich each project with its folder membership so the Projects setup
    // page (and any future project detail view) can render folder names,
    // paths, and roles without an extra round trip per project.
    let mut enriched = Vec::with_capacity(projects.len());
    for mut project in projects {
        let project_id = project["id"].as_str()
            .and_then(|s| uuid::Uuid::parse_str(s).ok());
        if let Some(pid) = project_id {
            let folders = state.pg.list_folders_by_project(&pid).await.unwrap_or_default();
            project["folders"] = serde_json::Value::Array(folders);
        } else {
            project["folders"] = serde_json::Value::Array(vec![]);
        }
        enriched.push(project);
    }
    Ok(Json(serde_json::json!(enriched)))
}

#[derive(Deserialize)]
pub(crate) struct CreateSolutionBody {
    name: String,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    client: Option<String>,
    // TODO: category and repos unused until maturity + repo membership is modeled
    #[serde(default = "default_category")]
    #[allow(dead_code)]
    category: String,
    #[serde(default)]
    #[allow(dead_code)]
    repos: Vec<CreateProjectRepo>,
}

#[derive(Deserialize)]
pub(crate) struct CreateProjectRepo {
    repo_id: String,
    #[serde(default = "default_role")]
    role: String,
    label: Option<String>,
}

fn default_category() -> String { "active".to_string() }
fn default_role() -> String { "unknown".to_string() }

pub(crate) async fn create_solution(
    State(state): State<AppState>,
    Json(body): Json<CreateSolutionBody>,
) -> Result<(StatusCode, Json<serde_json::Value>), StatusCode> {
    let id = state.pg.create_project(
        &body.name,
        body.description.as_deref(),
        body.client.as_deref(),
    ).await.map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    // TODO: repo-to-project membership not yet modeled.

    Ok((StatusCode::CREATED, Json(serde_json::json!({"ok": true, "id": id}))))
}

pub(crate) async fn update_solution(
    State(state): State<AppState>,
    Path(id): Path<String>,
    Json(body): Json<serde_json::Value>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;
    state.pg.update_project(
        &project_id,
        body["name"].as_str(),
        body["description"].as_str(),
        body["maturity"].as_str(),
    ).await.map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(serde_json::json!({"ok": true})))
}

pub(crate) async fn delete_solution(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;
    state.pg.delete_project(&project_id).await
        .map(|_| Json(serde_json::json!({"ok": true})))
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)
}

#[derive(serde::Deserialize)]
pub(crate) struct MergeProjectsBody {
    /// Project(s) whose folders + sessions + memories fold into `target`.
    /// Empty is an error. Deduped by the handler before running the merge.
    pub sources: Vec<String>,
    /// Destination project id. Must not appear in `sources`.
    pub target: String,
}

/// POST /api/projects/merge — merge one or more source projects into a
/// target project (#41). Derived signals (patterns / recommendations /
/// reasoning_traces / impact_verdicts) on the source projects are dropped
/// via ON DELETE CASCADE and regenerated by the analyzer on the next tick
/// over the merged corpus.
///
/// Returns `{ok: true, merged: <count>}` on success; per-source failures
/// short-circuit and roll back that source's transaction only (previously
/// merged sources stay merged).
pub(crate) async fn merge_projects(
    State(state): State<AppState>,
    Json(body): Json<MergeProjectsBody>,
) -> Result<Json<serde_json::Value>, (StatusCode, Json<serde_json::Value>)> {
    let target = uuid::Uuid::parse_str(&body.target)
        .map_err(|_| (StatusCode::BAD_REQUEST,
            Json(serde_json::json!({"error": "target is not a valid uuid"}))))?;

    // Parse + dedupe + reject self-references up front so the DB layer only
    // sees clean input.
    let mut sources: Vec<uuid::Uuid> = Vec::with_capacity(body.sources.len());
    for s in &body.sources {
        let uuid = uuid::Uuid::parse_str(s)
            .map_err(|_| (StatusCode::BAD_REQUEST,
                Json(serde_json::json!({"error": format!("source '{}' is not a valid uuid", s)}))))?;
        if uuid == target {
            return Err((StatusCode::BAD_REQUEST,
                Json(serde_json::json!({"error": "target must not appear in sources"}))));
        }
        if !sources.contains(&uuid) {
            sources.push(uuid);
        }
    }
    if sources.is_empty() {
        return Err((StatusCode::BAD_REQUEST,
            Json(serde_json::json!({"error": "sources must not be empty"}))));
    }

    let mut merged = 0u32;
    for src in &sources {
        state.pg.merge_projects(src, &target).await
            .map_err(|e| {
                tracing::error!(error = %e, source = %src, target = %target, "merge_projects failed");
                (StatusCode::INTERNAL_SERVER_ERROR,
                    Json(serde_json::json!({
                        "error": e,
                        "merged_before_failure": merged,
                    })))
            })?;
        merged += 1;
    }

    Ok(Json(serde_json::json!({ "ok": true, "merged": merged })))
}

pub(crate) async fn add_solution_repo(
    State(state): State<AppState>,
    Path(id): Path<String>,
    Json(body): Json<CreateProjectRepo>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;

    // Look up the folder by name (old string repo_id)
    let folder = state.pg.get_repo_by_name(&body.repo_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(StatusCode::NOT_FOUND)?;
    let folder_id = crate::api::util::json_uuid(&folder["id"])
        .ok_or(StatusCode::INTERNAL_SERVER_ERROR)?;

    state.pg.set_folder_project(&folder_id, &project_id, &body.role, body.label.as_deref()).await
        .map(|_| Json(serde_json::json!({"ok": true})))
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)
}

pub(crate) async fn remove_solution_repo(
    State(state): State<AppState>,
    Path((_id, repo_id)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    // Clear folder-project association by setting props to remove project link
    let folder = state.pg.get_repo_by_name(&repo_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(StatusCode::NOT_FOUND)?;
    let folder_id = crate::api::util::json_uuid(&folder["id"])
        .ok_or(StatusCode::INTERNAL_SERVER_ERROR)?;

    // Clear the project association by setting project_id to null via props
    state.pg.set_folder_props(&folder_id, &serde_json::json!({"project_id": null})).await
        .map(|_| Json(serde_json::json!({"ok": true})))
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)
}

pub(crate) async fn add_solution_tag(
    State(state): State<AppState>,
    Path(_id): Path<String>,
    Json(body): Json<TagBody>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    // PgStore tags are a controlled vocabulary. Register in vocabulary.
    state.pg.add_tag(&body.tag, Some("solution")).await
        .map(|_| Json(serde_json::json!({"ok": true})))
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)
}

pub(crate) async fn remove_solution_tag(
    State(state): State<AppState>,
    Path((_id, tag)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    // PgStore tags are a controlled vocabulary. Remove from vocabulary.
    state.pg.remove_tag(&tag).await
        .map(|_| Json(serde_json::json!({"ok": true})))
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)
}

// ── Solution Analysis ───────────────────────────────────────────────────────

pub(crate) async fn analyze_solution(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;
    let project = state.pg.get_project(&project_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(StatusCode::NOT_FOUND)?;

    // On-demand analyzer trigger (#67): enqueue session enrichment / analysis
    // for this project (the scheduler does this periodically). Task::new(kind,
    // folder_path, path) — the handler reads the project id from `path`.
    state.task_queue.enqueue(
        crate::tasks::Task::new(crate::tasks::TaskKind::AnalyzeProject, "", &id),
    ).await;

    // TODO: implement full cross-repo analysis
    Ok(Json(serde_json::json!({
        "project": project,
        "links": [],
        "shared_libs": [],
    })))
}

/// Enqueue a transcript backfill (#73) — ingest assistant/user prose from the
/// agent transcript caches into activity.transcript_turns. Resumable, so this
/// is safe to call repeatedly; only changed transcripts do work.
pub(crate) async fn backfill_transcripts(State(state): State<AppState>) -> Json<serde_json::Value> {
    let (files_seen, enqueued) = crate::transcript::dispatch(&state.task_queue).await;
    Json(serde_json::json!({ "ok": true, "files_seen": files_seen, "enqueued": enqueued }))
}

// ── Per-Repo Summary ────────────────────────────────────────────────────────

pub(crate) async fn project_summary(
    State(state): State<AppState>,
    Path(repo_id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    // Resolve to project-scoped folder ids; fall back to NOT_FOUND only if
    // neither a project name/UUID nor a repo name matches.
    let ids = state.pg.scope_folder_ids(&repo_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    if ids.is_empty() {
        return Err(StatusCode::NOT_FOUND);
    }

    // Derive counts across all folders in scope.
    let counts = state.pg.count_nodes_by_kind_scoped(&ids).await.unwrap_or_default();
    let fn_count = counts.get("function").copied().unwrap_or(0)
        + counts.get("method").copied().unwrap_or(0);
    let type_count = counts.get("class").copied().unwrap_or(0)
        + counts.get("struct").copied().unwrap_or(0)
        + counts.get("interface").copied().unwrap_or(0)
        + counts.get("enum").copied().unwrap_or(0)
        + counts.get("type").copied().unwrap_or(0);
    let edge_count = state.pg.count_edges_scoped(&ids).await.unwrap_or(0);
    let pkg_count = counts.get("package").copied().unwrap_or(0);
    let mod_count = counts.get("module").copied().unwrap_or(0);

    // Resolve name/path: prefer project row if repo_id is a project name/UUID,
    // else fall back to the first (root) folder row.
    let (name, path, stack, libs, tags, status, indexed_at) =
        if let Ok(Some(proj)) = state.pg.get_project_by_name(&repo_id).await {
            (
                proj["name"].clone(),
                proj.get("path").cloned().unwrap_or(serde_json::Value::Null),
                proj.get("stack").cloned().unwrap_or(serde_json::json!([])),
                serde_json::json!([]),
                proj.get("tags").cloned().unwrap_or(serde_json::json!([])),
                serde_json::json!("active"),
                serde_json::Value::Null,
            )
        } else if let Ok(Some(folder)) = state.pg.get_repo_by_name(&repo_id).await {
            (
                folder["name"].clone(),
                folder["abs_path"].clone(),
                folder.get("stack").cloned().unwrap_or(serde_json::json!([])),
                folder.get("libs").cloned().unwrap_or(serde_json::json!([])),
                folder.get("tags").cloned().unwrap_or(serde_json::json!([])),
                folder.get("status").cloned().unwrap_or(serde_json::json!("active")),
                folder.get("indexed_at").cloned().unwrap_or(serde_json::Value::Null),
            )
        } else {
            // UUID project lookup
            (
                serde_json::Value::String(repo_id.clone()),
                serde_json::Value::Null,
                serde_json::json!([]),
                serde_json::json!([]),
                serde_json::json!([]),
                serde_json::json!("active"),
                serde_json::Value::Null,
            )
        };

    Ok(Json(serde_json::json!({
        "repoId": name,
        "name": name,
        "path": path,
        "stack": stack,
        "libs": libs,
        "tags": tags,
        "status": status,
        "indexedAt": indexed_at,
        "functions": fn_count,
        "types": type_count,
        "packages": pkg_count,
        "modules": mod_count,
        "edges": edge_count,
        "solutions": [],
    })))
}

// ── Solution Graph & Roles ──────────────────────────────────────────────────

pub(crate) async fn solution_graph(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;
    let project = state.pg.get_project(&project_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(StatusCode::NOT_FOUND)?;

    let project_name = project["name"].as_str().unwrap_or("unknown");

    // Get all repos (folders) and filter those belonging to this project
    let all_repos = state.pg.list_repositories().await.unwrap_or_default();
    let project_repos: Vec<&serde_json::Value> = all_repos.iter()
        .filter(|r| r["project_id"].as_str() == Some(&id))
        .collect();

    let mut all_nodes = Vec::new();
    let mut all_edges = Vec::new();

    // Collect folder ids for all member repos, preserving per-repo metadata.
    let mut folder_ids: Vec<uuid::Uuid> = Vec::new();
    let mut folder_id_to_repo: std::collections::HashMap<uuid::Uuid, (&serde_json::Value, String)> =
        std::collections::HashMap::new();
    let mut seen_repo_ids = std::collections::HashSet::new();
    for repo in &project_repos {
        let repo_name = repo["name"].as_str().unwrap_or("").to_string();
        if !seen_repo_ids.insert(repo_name.clone()) {
            continue;
        }
        if let Some(fid) = crate::api::util::json_uuid(&repo["id"]) {
            folder_ids.push(fid);
            folder_id_to_repo.insert(fid, (repo, repo_name));
        }
    }

    // Fetch nodes and edges in one scoped call each.
    let scoped_nodes = state.pg.get_nodes_scoped(&folder_ids).await.unwrap_or_default();
    let scoped_edges = state.pg.get_edges_scoped(&folder_ids, "calls").await.unwrap_or_default();

    // Re-annotate nodes with repoId/role from folder metadata.
    // get_nodes_scoped returns folder_id — use it to look up the repo.
    for node in scoped_nodes {
        let fid_opt = node.get("folder_id")
            .and_then(|v| v.as_str())
            .and_then(|s| uuid::Uuid::parse_str(s).ok());
        let (repo_name, role) = fid_opt
            .and_then(|fid| folder_id_to_repo.get(&fid))
            .map(|(r, rn)| (rn.as_str(), r["role"].as_str().unwrap_or("unknown")))
            .unwrap_or(("", "unknown"));
        all_nodes.push(serde_json::json!({
            "id": node["id"], "name": node["name"], "kind": node["kind"],
            "file": node["file_path"], "line": node["line_start"],
            "complexity": node.get("complexity"),
            "doc_type": node.get("doc_type"), "level": node.get("level"),
            "parent_id": node["parent_id"],
            "repoId": repo_name, "role": role,
        }));
    }
    for edge in scoped_edges {
        // edges don't carry folder_id in the scoped result shape; repoId is best-effort
        all_edges.push(serde_json::json!({
            "source": edge["source_id"], "target": edge["target_id"],
            "type": "calls",
        }));
    }

    // Inject project-level hierarchy: soln -> repo nodes for each member
    let soln_node_id = format!("soln:{}", id);
    all_nodes.push(serde_json::json!({
        "id": &soln_node_id, "name": project_name, "kind": "solution",
        "file": "", "line": 0, "complexity": null,
    }));
    for repo in &project_repos {
        let repo_name = repo["name"].as_str().unwrap_or("");
        let repo_node_id = format!("repo:{}", repo_name);
        if !all_nodes.iter().any(|n| n.get("id").and_then(|v| v.as_str()) == Some(&repo_node_id)) {
            let label = repo["label"].as_str().unwrap_or(repo_name);
            let abs_path = repo["abs_path"].as_str().unwrap_or("");
            let role = repo["role"].as_str().unwrap_or("unknown");
            all_nodes.push(serde_json::json!({
                "id": &repo_node_id, "name": label, "kind": "repo",
                "file": abs_path, "line": 0, "complexity": null,
                "role": role,
            }));
        }
        all_edges.push(serde_json::json!({
            "source": &soln_node_id, "target": &repo_node_id, "type": "CONTAINS_REPO",
        }));
    }

    Ok(Json(serde_json::json!({
        "solutionId": id,
        "name": project_name,
        "nodes": all_nodes.len(),
        "edges": all_edges.len(),
        "repos": project_repos.len(),
        "graph": {"nodes": all_nodes, "edges": all_edges},
    })))
}

pub(crate) async fn solution_roles(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id)
        .map_err(|_| StatusCode::BAD_REQUEST)?;
    // Verify project exists
    state.pg.get_project(&project_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(StatusCode::NOT_FOUND)?;

    // Get repos belonging to this project
    let all_repos = state.pg.list_repositories().await.unwrap_or_default();
    let project_repos: Vec<serde_json::Value> = all_repos.into_iter()
        .filter(|r| r["project_id"].as_str() == Some(&id))
        .collect();

    // Build simple role list from folder data
    let roles: Vec<serde_json::Value> = project_repos.iter().map(|r| {
        serde_json::json!({
            "repoId": r["name"],
            "role": r.get("role").and_then(|v| v.as_str()).unwrap_or("unknown"),
            "label": r.get("label").and_then(|v| v.as_str()),
        })
    }).collect();

    Ok(Json(serde_json::json!(roles)))
}

// ── Metrics ─────────────────────────────────────────────────────────────────

pub(crate) async fn get_metrics(
    State(state): State<AppState>,
    Path(project): Path<String>,
) -> Json<serde_json::Value> {
    // Metrics are computed from session data in PgStore.
    // Look up folder to get its UUID, then query sessions.
    let folder = state.pg.get_repo_by_name(&project).await.ok().flatten();
    if let Some(folder) = folder
        && let Some(folder_id) = crate::api::util::json_uuid(&folder["id"]) {
            let sessions = state.pg.list_sessions_by_folder(&folder_id, 100).await.unwrap_or_default();
            let session_count = sessions.len();
            let completed = sessions.iter().filter(|s| s["outcome"].as_str() == Some("completed")).count();
            return Json(serde_json::json!({
                "project": project,
                "sessions": session_count,
                "completed": completed,
                "ftr": if session_count > 0 { completed as f64 / session_count as f64 } else { 0.0 },
            }));
        }
    Json(serde_json::json!({"error": "project not found"}))
}

// ── Observatory Chart Data ─────────────────────────────────────────────────

#[derive(Deserialize)]
pub(crate) struct DaysQuery {
    #[serde(default = "default_days")]
    days: i32,
}
fn default_days() -> i32 { 14 }

#[derive(Deserialize)]
pub(crate) struct LimitQuery {
    #[serde(default = "default_limit")]
    limit: i64,
}
fn default_limit() -> i64 { 10 }

/// GET /api/observatory/ftr-daily?days=14 — holistic FTR sparkline (all projects)
pub(crate) async fn holistic_ftr_daily(
    State(state): State<AppState>,
    axum::extract::Query(q): axum::extract::Query<DaysQuery>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let data = state.pg.get_ftr_daily(None, q.days).await
        .map_err(|e| { tracing::error!("ftr_daily error: {}", e); StatusCode::INTERNAL_SERVER_ERROR })?;
    Ok(Json(serde_json::json!({ "ftr_daily": data })))
}

/// GET /api/projects/{id}/ftr-daily?days=14 — per-project FTR sparkline
pub(crate) async fn project_ftr_daily(
    State(state): State<AppState>,
    Path(id): Path<String>,
    axum::extract::Query(q): axum::extract::Query<DaysQuery>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let data = state.pg.get_ftr_daily(Some(&project_id), q.days).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(serde_json::json!({ "ftr_daily": data })))
}

/// GET /api/projects/{id}/hotspots?days=7 — files with highest rework
pub(crate) async fn project_hotspots(
    State(state): State<AppState>,
    Path(id): Path<String>,
    axum::extract::Query(q): axum::extract::Query<DaysQuery>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let data = state.pg.get_hotspots(&project_id, q.days).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(serde_json::json!({ "hotspots": data })))
}

/// GET /api/projects/{id}/quality-signals — 4 quality indicators
pub(crate) async fn project_quality_signals(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let data = state.pg.get_quality_signals(&project_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(data))
}

/// GET /api/projects/{id}/maturity — the derived early/mature signal (#71)
/// plus watched/target progress. Not the stored `projects.maturity` lifecycle
/// enum; computed on read from enriched-session count + insight presence.
pub(crate) async fn project_maturity(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let (watched, has_insights) = state
        .pg
        .get_project_maturity_inputs(&project_id)
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    let sig =
        crate::maturity::maturity_signal(watched, has_insights, crate::maturity::MATURITY_TARGET);
    Ok(Json(serde_json::json!({
        "stage": sig.stage,
        "watched": sig.watched,
        "target": sig.target,
        "hasInsights": sig.has_insights,
    })))
}

/// GET /api/observatory/tool-usage — tool usage across all sessions
pub(crate) async fn tool_usage(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let data = state.pg.get_tool_usage_stats().await
        .map_err(|e| { tracing::error!("tool_usage error: {}", e); StatusCode::INTERNAL_SERVER_ERROR })?;
    Ok(Json(serde_json::json!({ "tools": data })))
}

/// GET /api/observatory/tool-signals — derived insight cards.
///
/// Prefers the cached snapshots written by the `AggregateToolInsights`
/// scheduled task (T2 Slice D); falls back to computing on the fly when
/// the cache is empty (fresh install, task hasn't run yet). The wire
/// shape stays identical either way — `{ signals: [{tool_name, variant,
/// title, detail}] }` — so callers don't care where the data came from.
pub(crate) async fn tool_signals(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    use crate::api::handlers::tool_signals as ts;

    // Fast path: read the cached snapshot the scheduled task writes.
    let cached = state.pg.get_latest_tool_insights().await
        .map_err(|e| { tracing::error!(error = %e, "tool_signals: get_latest_tool_insights failed"); StatusCode::INTERNAL_SERVER_ERROR })?;
    let cached_signals: Vec<serde_json::Value> = cached.iter()
        .filter(|row| row.get("variant").and_then(|v| v.as_str()).is_some())
        .map(|row| serde_json::json!({
            "tool_name": row.get("toolName").cloned().unwrap_or(serde_json::Value::Null),
            "variant":   row.get("variant").cloned().unwrap_or(serde_json::Value::Null),
            "title":     row.get("title").cloned().unwrap_or(serde_json::Value::Null),
            "detail":    row.get("detail").cloned().unwrap_or(serde_json::Value::Null),
        }))
        .collect();
    if !cached_signals.is_empty() {
        return Ok(Json(serde_json::json!({ "signals": cached_signals, "source": "cache" })));
    }

    // Fallback: derive on-the-fly. Same heuristics as the scheduled task
    // so empty-cache and populated-cache paths produce identical cards.
    let rows = state.pg.get_tool_usage_stats().await
        .map_err(|e| { tracing::error!(error = %e, "tool_signals: get_tool_usage_stats failed"); StatusCode::INTERNAL_SERVER_ERROR })?;
    let stats: Vec<ts::ToolUsageRow> = rows.into_iter()
        .filter_map(|v| serde_json::from_value(v).ok())
        .collect();
    let signals = ts::derive_signals(&stats, chrono::Utc::now(), &ts::SignalThresholds::default());
    Ok(Json(serde_json::json!({ "signals": signals, "source": "derived" })))
}

/// GET /api/observatory/tool-insights — full cached snapshot per tool,
/// including metrics + signal (if any) + computed_at. Powers the Health
/// tab's per-tool detail pane and future trend charts.
pub(crate) async fn tool_insights(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let rows = state.pg.get_latest_tool_insights().await
        .map_err(|e| { tracing::error!(error = %e, "tool_insights: get_latest_tool_insights failed"); StatusCode::INTERNAL_SERVER_ERROR })?;
    Ok(Json(serde_json::json!({ "insights": rows })))
}

/// GET /api/observatory/model-effectiveness — FTR / corrections / volume per
/// (provider, model) across the multi-model corpus (Zed + Claude). Powers the
/// "which models work best here" view.
pub(crate) async fn model_effectiveness(
    State(state): State<AppState>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let data = state.pg.get_model_effectiveness().await
        .map_err(|e| { tracing::error!("model_effectiveness error: {}", e); StatusCode::INTERNAL_SERVER_ERROR })?;
    Ok(Json(serde_json::json!({ "models": data })))
}

/// GET /api/libraries/{id}/usage — per-library usage across folders
pub(crate) async fn library_usage(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let library_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let data = state.pg.get_library_usage(&library_id).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(serde_json::json!({ "usage": data })))
}

/// GET /api/projects/{id}/teachings?limit=10 — adopted rules
pub(crate) async fn project_teachings(
    State(state): State<AppState>,
    Path(id): Path<String>,
    axum::extract::Query(q): axum::extract::Query<LimitQuery>,
) -> Result<Json<serde_json::Value>, StatusCode> {
    let project_id = uuid::Uuid::parse_str(&id).map_err(|_| StatusCode::BAD_REQUEST)?;
    let data = state.pg.get_adopted_teachings(&project_id, q.limit).await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(serde_json::json!({ "teachings": data })))
}
