export function claudeMdTemplate(opts: {
  repoName: string;
  stack: string[];
  repoId: string;
}): string {
  return `# Project Context — ${opts.repoName}

> Auto-generated by sensei. Update as needed.

## Orientation
Call \`get_session_context()\` to resume a session.
Call \`get_llmspec()\` for full repo orientation.

## Stack
${opts.stack.map(s => `- ${s}`).join("\n")}

## Shortcuts
See \`.sensei/shortcuts.md\`

## Patterns
See \`.sensei/patterns.md\`
`;
}
