export function claudeMdTemplate(opts: {
  repoName: string;
  stack: string[];
  repoId: string;
}): string {
  return `# Project Context — ${opts.repoName}

> Auto-generated by sensei. Update as needed.

## Orientation
Call \`get_session_context()\` to resume a session.
Call \`get_llmspec()\` for full repo orientation.

## Stack
${opts.stack.map(s => `- ${s}`).join("\n")}

## Shortcuts
See \`.sensei/shortcuts.md\`

## Patterns
See \`.sensei/patterns.md\`

## Code Quality Policy

**Zero Errors Policy:** Before starting any implementation task, run the full test suite and TypeScript check. Fix ALL errors before writing new code. After completing any task, run again — zero errors means zero, not "same as before". Use the \`zero-errors-policy\` skill.

\`\`\`
Checkpoint 1 (before coding): bun run --filter '*' test && bunx tsc --noEmit
Checkpoint 2 (after coding):  bun run --filter '*' test && bunx tsc --noEmit
\`\`\`
`;
}
