// Auto-generated by @kavach/vite — do not edit.
// Safe to add to .gitignore.

declare module '$kavach/auth' {
	import type { AuthAdapter } from 'kavach'
	export const kavach: {
		handle: (input: { event: any; resolve: any }) => Response | Promise<Response>
		signIn: (credentials: any) => Promise<any>
		signUp: (credentials: any) => Promise<any>
		signOut: () => Promise<any>
		onAuthChange: () => any
		configure: (options?: {
			invalidateAll?: () => void
			logger?: unknown
			/** Called on the server with the INCOMING provider session at sign-in —
			 *  the only moment fields such as provider_token exist. Nothing extra
			 *  is persisted; a throw here never fails the sign-in. */
			onSessionSync?: (session: any, event: string) => unknown
		}) => void
		actions: (schema?: string) => any
		getCachedLogins: () => any[]
		removeCachedLogin: (email: string) => void
		clearCachedLogins: () => void
	}
	export const adapter: AuthAdapter
	export const logger: unknown
}

declare module '$kavach/config' {
	export const config: {
		adapter: string
		cachedLogins: boolean
		logging: { level: string; table?: string; collection?: string; entity?: string }
		routes: Record<string, unknown>
		endpoints: { data: boolean; rpc: boolean }
		messages: Record<string, string>
	}
}

declare module '$kavach/routes' {
	export const routes: {
		paths: Record<string, unknown>
		rules: Array<Record<string, unknown>>
	}
}

declare module '$kavach/providers' {
	export const providers: Array<{
		name: string
		mode?: 'otp' | 'oauth' | 'password'
		label: string
	}>
}
