set search_path to sensei, extensions;

-- Skills a library provides. Two writers coexist, distinguished by `source`:
--   'manifest'  — declared in the library's own sensei.library.json (workstream D).
--   'generated' — auto-generated from usage/docs (library-intelligence.md skill-gen).
-- Associated to any project that depends on the library (via referenced_libraries /
-- project_libraries) so the recommender can surface them. Keyed unique on
-- (library_id, name); `focus` is the topic selector for get_library_skill.
create table if not exists library_skills (
  id            uuid          primary key default gen_random_uuid()
, library_id    uuid          not null references sensei.libraries(id) on delete cascade
, name          text          not null
, focus         text          not null
, body          text
, source        text          not null default 'manifest'
, source_path   text
, version_range text
, tokens        integer
, generated_at  timestamptz
, modified_at   timestamptz   not null default now()
, unique(library_id, name)
);

create index if not exists library_skills_library_id_idx
    on library_skills(library_id);

comment on table library_skills is
'Skills a library provides — from its sensei.library.json manifest (source=manifest,
workstream D) or auto-generated by sensei (source=generated, library-intelligence.md).
Surfaced for any project depending on the library. Unique on (library_id, name).';
comment on column library_skills.library_id is 'FK to libraries — which library ships this skill.';
comment on column library_skills.name       is 'Skill name — unique within a library.';
comment on column library_skills.focus      is 'Short topic key (e.g. "styling") — the selector arg to get_library_skill.';
comment on column library_skills.body       is 'The skill markdown, fetched from the manifest path at ingest so reads are self-contained.';
comment on column library_skills.source     is 'Provenance: manifest (declared in sensei.library.json) | generated (auto-generated).';
comment on column library_skills.source_path is 'Manifest-relative path the body was read from (provenance). Null for generated.';
comment on column library_skills.version_range is 'Semver range (from the manifest) these capabilities apply to. Free text in v1; not enforced-matched.';
comment on column library_skills.tokens     is 'Approx token size — library-intelligence.md field; null until skill-gen.';
comment on column library_skills.generated_at is 'When auto-generated — library-intelligence.md field; null for manifest skills.';
comment on column library_skills.modified_at is 'Timestamp of the last modification to this row.';
