-- communities
-- Leiden community detection results over the symbol graph.
-- Populated by the engine after each full index run (incremental runs update degree
-- but defer community recomputation to a background job or explicit request).
--
-- One row per detected community. community_id is a stable label (integer, assigned
-- by Leiden in order of size descending so community 0 is always the largest).
--
-- label / description: human-readable name and summary generated by local inference
-- (Gemma) or derived heuristically from the most common symbol name prefix.
--
-- god_node_ids: JSON array of the top-5 highest-degree symbol ids in this community.
-- These are the "load-bearing" concepts that everything else connects through.

create table if not exists communities (
  id              text    not null primary key
, community_id    integer not null   -- Leiden-assigned integer label
, label           text               -- human-readable name (e.g. "Authentication", "API Layer")
, description     text               -- one-paragraph summary
, symbol_count    integer not null default 0
, god_node_ids    text    not null default '[]'  -- JSON: top-5 symbol ids by degree
, computed_at     text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
, modified_at     text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
, modified_by     text    not null default 'system'
, unique(community_id)
);

create index if not exists communities_size_idx on communities(symbol_count desc);
